name: Java CI Checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint_and_style:
    name: Lint and Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Spotless Check
        run: mvn spotless:check -B

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint_and_style
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven Tests
        run: mvn test -B
